### ISSUE TITLE
Files (PDF) are not displayed in the Contao "Downloads" element in the backend. 

### ISSUE THREAD

**Issue by padgrob** [pdir/animated-timeline-bundle#13]
## Bug description
Files (PDF) are not displayed in the Contao "Downloads" element in the backend. 
In the frontend, the PDF files are displayed correctly and can be downloaded without any problems.

Currently the problem only occurs with .pdf files. Images (.jpg or .webp) are displayed correctly.

## Screenshots

![be1](https://github.com/pdir/animated-timeline-bundle/assets/11654144/a2636379-23e1-4bb8-8b71-e6e833da1ffa)
![be2](https://github.com/pdir/animated-timeline-bundle/assets/11654144/fd558cf3-b245-464a-ace3-c5cb204c551c)
![be3](https://github.com/pdir/animated-timeline-bundle/assets/11654144/5b5b90c4-0c39-497c-b3f7-62e06ea62496)

## Environment

contao/manager-bundle Version 4.13.44
pdir/animated-timeline-bundle Version1.3
PHP 8.2.19

**Comment by fritzmg** [comment]
The cause is this line: https://github.com/pdir/animated-timeline-bundle/blob/abe1d8eb298099443308678bd13c351352215d7a/contao/dca/tl_content.php#L130

@MDevster @seibtph you must not set this for the `tl_content.multiSRC` field in general. Instead you need to do this via a `fields.multiSRC.load` callback any only set it for the content element in question (just like [the core does](https://github.com/contao/contao/blob/f9caff0ccfae2a96bf87810427bc93aecb6b7058/core-bundle/src/Resources/contao/dca/tl_content.php#L1874C18-L1895)).

**Comment by padgrob** [comment]
Is there any news on this problem?
Or a temporary fix in the source code of the plugin?

**Comment by fritzmg** [comment]
You could finance a PR, if nobody else provides one.

**Comment by leon1995** [comment]
Would be great. This also affects newer contao versions (5.3.x ...)

**Comment by leon1995** [comment]
I created a pr. Please check whether this is the solution you suggested @fritzmg
